//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CultureExplorer20.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CultureExplorer20.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Cultures.
        /// </summary>
        internal static string AllCultures {
            get {
                return ResourceManager.GetString("AllCultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Lunisolar Calendar.
        /// </summary>
        internal static string ChineseLunisolarCalendar {
            get {
                return ResourceManager.GetString("ChineseLunisolarCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyMenu {
            get {
                return ResourceManager.GetString("CopyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon cultureExplorer {
            get {
                object obj = ResourceManager.GetObject("cultureExplorer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom User Cultures.
        /// </summary>
        internal static string CustomUserCultures {
            get {
                return ResourceManager.GetString("CustomUserCultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d ShortDatePattern.
        /// </summary>
        internal static string DateFormat_D {
            get {
                return ResourceManager.GetString("DateFormat_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D LongDatePattern.
        /// </summary>
        internal static string DateFormat_DC {
            get {
                return ResourceManager.GetString("DateFormat_DC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f Full date and time (long date and short time).
        /// </summary>
        internal static string DateFormat_F {
            get {
                return ResourceManager.GetString("DateFormat_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F FullDateTimePattern (long date and long time).
        /// </summary>
        internal static string DateFormat_FC {
            get {
                return ResourceManager.GetString("DateFormat_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g General (short date and short time).
        /// </summary>
        internal static string DateFormat_G {
            get {
                return ResourceManager.GetString("DateFormat_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G General (short date and long time).
        /// </summary>
        internal static string DateFormat_GC {
            get {
                return ResourceManager.GetString("DateFormat_GC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m, M MonthDayPattern.
        /// </summary>
        internal static string DateFormat_M {
            get {
                return ResourceManager.GetString("DateFormat_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r, R RFC1123 Pattern.
        /// </summary>
        internal static string DateFormat_R {
            get {
                return ResourceManager.GetString("DateFormat_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s SortableDateTimePattern using local time.
        /// </summary>
        internal static string DateFormat_S {
            get {
                return ResourceManager.GetString("DateFormat_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t ShortTimePattern.
        /// </summary>
        internal static string DateFormat_T {
            get {
                return ResourceManager.GetString("DateFormat_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T LongTimePattern.
        /// </summary>
        internal static string DateFormat_TC {
            get {
                return ResourceManager.GetString("DateFormat_TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to u UniversalSortableDateTimePattern using universal time.
        /// </summary>
        internal static string DateFormat_U {
            get {
                return ResourceManager.GetString("DateFormat_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U Full date and time using universal time.
        /// </summary>
        internal static string DateFormat_UC {
            get {
                return ResourceManager.GetString("DateFormat_UC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y, Y YearMonthPattern.
        /// </summary>
        internal static string DateFormat_Y {
            get {
                return ResourceManager.GetString("DateFormat_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        internal static string DigitShapesContext {
            get {
                return ResourceManager.GetString("DigitShapesContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native National.
        /// </summary>
        internal static string DigitShapesNativeNational {
            get {
                return ResourceManager.GetString("DigitShapesNativeNational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string DigitShapesNone {
            get {
                return ResourceManager.GetString("DigitShapesNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East Asian Lunisolar Calendar.
        /// </summary>
        internal static string EastAsianLunisolarCalendar {
            get {
                return ResourceManager.GetString("EastAsianLunisolarCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mailto:francl@microsoft.com?subject=Culture Explorer 2.0.
        /// </summary>
        internal static string EmailInfo {
            get {
                return ResourceManager.GetString("EmailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework Cultures.
        /// </summary>
        internal static string FrameworkCultures {
            get {
                return ResourceManager.GetString("FrameworkCultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gregorian Calendar.
        /// </summary>
        internal static string GregorianCalendar {
            get {
                return ResourceManager.GetString("GregorianCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string GregorianNameFormat {
            get {
                return ResourceManager.GetString("GregorianNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        internal static string GregorianTypeArabic {
            get {
                return ResourceManager.GetString("GregorianTypeArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localized.
        /// </summary>
        internal static string GregorianTypeLocalized {
            get {
                return ResourceManager.GetString("GregorianTypeLocalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle-East French.
        /// </summary>
        internal static string GregorianTypeMiddleEastFrench {
            get {
                return ResourceManager.GetString("GregorianTypeMiddleEastFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transliterated English.
        /// </summary>
        internal static string GregorianTypeTransliteratedEnglish {
            get {
                return ResourceManager.GetString("GregorianTypeTransliteratedEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transliterated French.
        /// </summary>
        internal static string GregorianTypeTransliteratedFrench {
            get {
                return ResourceManager.GetString("GregorianTypeTransliteratedFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US English.
        /// </summary>
        internal static string GregorianTypeUSEnglish {
            get {
                return ResourceManager.GetString("GregorianTypeUSEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew Calendar.
        /// </summary>
        internal static string HebrewCalendar {
            get {
                return ResourceManager.GetString("HebrewCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hijiri Calendar.
        /// </summary>
        internal static string HijriCalendar {
            get {
                return ResourceManager.GetString("HijriCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Windows Cultures.
        /// </summary>
        internal static string InstalledWin32Cultures {
            get {
                return ResourceManager.GetString("InstalledWin32Cultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Invariant].
        /// </summary>
        internal static string Invariant {
            get {
                return ResourceManager.GetString("Invariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese Calendar.
        /// </summary>
        internal static string JapaneseCalendar {
            get {
                return ResourceManager.GetString("JapaneseCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese Lunisolar Calendar.
        /// </summary>
        internal static string JapaneseLunisolarCalendar {
            get {
                return ResourceManager.GetString("JapaneseLunisolarCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julian Calendar.
        /// </summary>
        internal static string JulianCalendar {
            get {
                return ResourceManager.GetString("JulianCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean Calendar.
        /// </summary>
        internal static string KoreanCalendar {
            get {
                return ResourceManager.GetString("KoreanCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean Lunisolar Calendar.
        /// </summary>
        internal static string KoreanLunisolarCalendar {
            get {
                return ResourceManager.GetString("KoreanLunisolarCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunar.
        /// </summary>
        internal static string LunarCalendarType {
            get {
                return ResourceManager.GetString("LunarCalendarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luni-Solar.
        /// </summary>
        internal static string LuniSolarCalendarType {
            get {
                return ResourceManager.GetString("LuniSolarCalendarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral Cultures.
        /// </summary>
        internal static string NeutralCultures {
            get {
                return ResourceManager.GetString("NeutralCultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E Scientific format.
        /// </summary>
        internal static string NumberFormat_EC {
            get {
                return ResourceManager.GetString("NumberFormat_EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F Fixed-point format.
        /// </summary>
        internal static string NumberFormat_FC {
            get {
                return ResourceManager.GetString("NumberFormat_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G General format.
        /// </summary>
        internal static string NumberFormat_GC {
            get {
                return ResourceManager.GetString("NumberFormat_GC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N Number format.
        /// </summary>
        internal static string NumberFormat_NC {
            get {
                return ResourceManager.GetString("NumberFormat_NC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Roundtrip format.
        /// </summary>
        internal static string NumberFormat_RC {
            get {
                return ResourceManager.GetString("NumberFormat_RC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian Calendar.
        /// </summary>
        internal static string PersianCalendar {
            get {
                return ResourceManager.GetString("PersianCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement Cultures.
        /// </summary>
        internal static string ReplacementCultures {
            get {
                return ResourceManager.GetString("ReplacementCultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar.
        /// </summary>
        internal static string SolarCalendarType {
            get {
                return ResourceManager.GetString("SolarCalendarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Cultures.
        /// </summary>
        internal static string SpecificCultures {
            get {
                return ResourceManager.GetString("SpecificCultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taiwan Calendar.
        /// </summary>
        internal static string TaiwanCalendar {
            get {
                return ResourceManager.GetString("TaiwanCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taiwan LuniSolar Calendar.
        /// </summary>
        internal static string TaiwanLunisolarCalendar {
            get {
                return ResourceManager.GetString("TaiwanLunisolarCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai Buddhist Calendar.
        /// </summary>
        internal static string ThaiBuddhistCalendar {
            get {
                return ResourceManager.GetString("ThaiBuddhistCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TreeViewIcons {
            get {
                object obj = ResourceManager.GetObject("TreeViewIcons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi Hijiri (Umm-Al Qurah) Calendar.
        /// </summary>
        internal static string UmAlQuraCalendar {
            get {
                return ResourceManager.GetString("UmAlQuraCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string UnknowCalendarType {
            get {
                return ResourceManager.GetString("UnknowCalendarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows-Only Cultures.
        /// </summary>
        internal static string WindowsOnlyCultures {
            get {
                return ResourceManager.GetString("WindowsOnlyCultures", resourceCulture);
            }
        }
    }
}
